version: "3"

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go run github.com/a-h/templ/cmd/templ@v0.3.1001 generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/pi-ntop" --open-browser=false

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - |
        TEMPLUI_PATH="$(go list -mod=mod -m -f {{`'{{.Dir}}'`}} github.com/templui/templui)" && \
        printf '%s\n' \
          '@source "./**/*.templ";' \
          "@source \"$TEMPLUI_PATH/components/**/*.templ\";" \
          > ./assets/css/sources.generated.css && \
        tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ